use calvin_core::context::TypeContext;
use calvin_core::lang::expr::{Expr, Pattern};
use calvin_core::lang::typeclass::TypeClassRegistry;
use calvin_core::lang::typeinf::TypeEnv;
use calvin_core::lang::types::{MonoType, Prim};
use calvin_parse::ast::{ModuleDef, TypeExpr, VarTypeDef};
use calvin_parse::parse_module;
use std::collections::HashMap;
use std::rc::Rc;

// Generated by build.rs: embeds all boot/*.hob scripts in alphabetical order
include!(concat!(env!("OUT_DIR"), "/boot_scripts.rs"));

pub fn boot_script(name: &str) -> Option<&'static str> {
    BOOT_SCRIPTS
        .iter()
        .find(|(n, _)| *n == name)
        .map(|(_, content)| *content)
}

const NUMERIC_CONVERSIONS: &[(&str, Prim, Prim)] = &[
    ("b2i", Prim::Byte, Prim::Int),
    ("b2l", Prim::Byte, Prim::Long),
    ("s2i", Prim::Short, Prim::Int),
    ("i2l", Prim::Int, Prim::Long),
    ("i2d", Prim::Int, Prim::Double),
    ("i2f", Prim::Int, Prim::Float),
    ("l2d", Prim::Long, Prim::Double),
    ("l2f", Prim::Long, Prim::Float),
    ("f2d", Prim::Float, Prim::Double),
    ("l2i16", Prim::Long, Prim::Int128),
];

const BUILTIN_PASSTHROUGH_FNS: &[&str] = &[
    "id", "convert", "b2i", "b2l", "s2i", "i2l", "i2d", "i2f", "l2d", "l2f", "f2d", "l2i16",
];

/// Helper to strip enclosing parentheses from operator names (e.g. `(+)` -> `+`).
fn strip_parens(name: &str) -> &str {
    if name.starts_with('(') && name.ends_with(')') && name.len() >= 3 {
        &name[1..name.len() - 1]
    } else {
        name
    }
}

/// Helper to construct curried lambda functions from argument lists.
fn curry_fn<'ctx>(
    ctx: &'ctx TypeContext,
    args: &[&'ctx str],
    body: &'ctx Expr<'ctx>,
) -> &'ctx Expr<'ctx> {
    if args.is_empty() {
        body
    } else {
        args.iter().rev().fold(body, |acc, &arg| {
            &*ctx.alloc(Expr::Fn(Pattern::Var(arg), acc))
        })
    }
}

fn init_builtin_env<'ctx>(
    ctx: &'ctx TypeContext,
    base_env: &mut TypeEnv<'ctx>,
    registry: &mut TypeClassRegistry<'ctx>,
) {
    let bool_ty: &'ctx MonoType<'ctx> = &*ctx.alloc(MonoType::Prim(Prim::Bool));
    let tup = ctx.alloc(MonoType::Tuple(
        ctx.arena().alloc_slice_clone(&[bool_ty, bool_ty]),
    ));
    let tup_to_bool = ctx.alloc(MonoType::Fn(tup, bool_ty));
    let bool_to_bool = ctx.alloc(MonoType::Fn(bool_ty, bool_ty));

    base_env.insert("and", tup_to_bool);
    base_env.insert("or", tup_to_bool);
    base_env.insert("not", bool_to_bool);

    // Identity and conversion primitives matching Hobbes
    let tgen0: &'ctx MonoType<'ctx> = &*ctx.alloc(MonoType::TGen(0));
    let tgen1: &'ctx MonoType<'ctx> = &*ctx.alloc(MonoType::TGen(1));
    base_env.insert("id", ctx.alloc(MonoType::Fn(tgen0, tgen0)));

    for &(op, from_prim, to_prim) in NUMERIC_CONVERSIONS {
        let from_ty = ctx.alloc(MonoType::Prim(from_prim));
        let to_ty = ctx.alloc(MonoType::Prim(to_prim));
        base_env.insert(op, ctx.alloc(MonoType::Fn(from_ty, to_ty)));
    }

    // Hobbes builtin primitive type class: Convert a b => (a) -> b
    registry.register_class("Convert", vec!["a", "b"], Vec::new(), HashMap::new());

    let type_params = ctx.arena().alloc_slice_clone(&[tgen0, tgen1]);
    let a_to_b = ctx.alloc(MonoType::Fn(tgen0, tgen1));
    let convert_cst_ty = ctx.alloc(MonoType::Constraint("Convert", type_params, a_to_b));
    base_env.insert("convert", convert_cst_ty);
}

pub type RawBootEnvParts<'ctx> = (
    Rc<TypeEnv<'ctx>>,
    Rc<TypeClassRegistry<'ctx>>,
    Rc<HashMap<String, &'ctx Expr<'ctx>>>,
);

pub fn init_bootstrap_with_defs<'ctx>(
    ctx: &'ctx TypeContext,
) -> Result<RawBootEnvParts<'ctx>, String> {
    let mut base_env = TypeEnv::new();
    let mut registry = TypeClassRegistry::new();
    let mut fn_defs = HashMap::new();

    // 0. Initialize built-in macro/std functions matching Hobbes
    init_builtin_env(ctx, &mut base_env, &mut registry);

    let id_fn = &*ctx.alloc(Expr::Fn(Pattern::Var("x"), ctx.alloc(Expr::Var("x"))));
    for &fn_name in BUILTIN_PASSTHROUGH_FNS {
        fn_defs.insert(fn_name.to_string(), id_fn);
    }

    // 1. Process all boot scripts in alphabetical order
    for (_name, content) in BOOT_SCRIPTS {
        if let Ok(module) = parse_module(ctx, content) {
            load_module_defs(
                ctx,
                module.defs(),
                &mut base_env,
                &mut registry,
                &mut fn_defs,
            );
        }
    }

    Ok((Rc::new(base_env), Rc::new(registry), Rc::new(fn_defs)))
}

/// Aggregate Root representing the fully initialized Calvin/Hobbes bootstrap environment.
#[derive(Clone)]
pub struct BootEnvironment<'ctx> {
    env: Rc<TypeEnv<'ctx>>,
    registry: Rc<TypeClassRegistry<'ctx>>,
    fn_defs: Rc<HashMap<String, &'ctx Expr<'ctx>>>,
}

impl<'ctx> BootEnvironment<'ctx> {
    pub fn new(
        env: Rc<TypeEnv<'ctx>>,
        registry: Rc<TypeClassRegistry<'ctx>>,
        fn_defs: Rc<HashMap<String, &'ctx Expr<'ctx>>>,
    ) -> Self {
        Self {
            env,
            registry,
            fn_defs,
        }
    }

    pub fn env(&self) -> &Rc<TypeEnv<'ctx>> {
        &self.env
    }

    pub fn registry(&self) -> &Rc<TypeClassRegistry<'ctx>> {
        &self.registry
    }

    pub fn fn_defs(&self) -> &Rc<HashMap<String, &'ctx Expr<'ctx>>> {
        &self.fn_defs
    }

    pub fn fn_def(&self, name: &str) -> Option<&'ctx Expr<'ctx>> {
        self.fn_defs.get(name).copied()
    }

    pub fn into_parts(
        self,
    ) -> (
        Rc<TypeEnv<'ctx>>,
        Rc<TypeClassRegistry<'ctx>>,
        Rc<HashMap<String, &'ctx Expr<'ctx>>>,
    ) {
        (self.env, self.registry, self.fn_defs)
    }
}

pub fn init_boot_environment<'ctx>(
    ctx: &'ctx TypeContext,
) -> Result<BootEnvironment<'ctx>, String> {
    let (env, reg, fn_defs) = init_bootstrap_with_defs(ctx)?;
    Ok(BootEnvironment::new(env, reg, fn_defs))
}

pub fn init_bootstrap<'ctx>(
    ctx: &'ctx TypeContext,
) -> Result<(Rc<TypeEnv<'ctx>>, Rc<TypeClassRegistry<'ctx>>), String> {
    let (env, reg, _) = init_bootstrap_with_defs(ctx)?;
    Ok((env, reg))
}

fn load_module_defs<'ctx>(
    ctx: &'ctx TypeContext,
    defs: &[ModuleDef<'ctx>],
    base_env: &mut TypeEnv<'ctx>,
    registry: &mut TypeClassRegistry<'ctx>,
    fn_defs: &mut HashMap<String, &'ctx Expr<'ctx>>,
) {
    for def in defs {
        match def {
            ModuleDef::Class(class_def) => {
                load_class_def(ctx, class_def, base_env, registry);
            }
            ModuleDef::Instance(inst_def) => {
                load_instance_def(ctx, inst_def, registry, fn_defs);
            }
            ModuleDef::VarType(vtd) => {
                load_var_type_def(ctx, vtd, base_env);
            }
            ModuleDef::VarDef(vd) => {
                load_var_def(ctx, vd, fn_defs);
            }
            ModuleDef::Data(_) => {
                // Type alias / data vector definitions in boot scripts
            }
        }
    }
}

fn load_class_def<'ctx>(
    ctx: &'ctx TypeContext,
    class_def: &calvin_parse::ast::ClassDef<'ctx>,
    base_env: &mut TypeEnv<'ctx>,
    registry: &mut TypeClassRegistry<'ctx>,
) {
    let mut fundeps = Vec::new();
    for (from_names, to_names) in &class_def.fundeps {
        let from_indices: Vec<usize> = from_names
            .iter()
            .filter_map(|name| class_def.params.iter().position(|p| p == name))
            .collect();
        let to_indices: Vec<usize> = to_names
            .iter()
            .filter_map(|name| class_def.params.iter().position(|p| p == name))
            .collect();
        fundeps.push((from_indices, to_indices));
    }

    registry.register_class(
        class_def.name,
        class_def.params.clone(),
        fundeps,
        HashMap::new(),
    );

    let mut var_map = HashMap::new();
    let gen_tys: Vec<&'ctx MonoType<'ctx>> = (0..class_def.params.len())
        .map(|i| {
            let g = &*ctx.alloc(MonoType::TGen(i));
            var_map.insert(class_def.params[i], g);
            g
        })
        .collect();
    let gen_slice = ctx.arena().alloc_slice_clone(&gen_tys);

    for member in &class_def.members {
        let op_name = strip_parens(member.name);

        let inner_fn = if class_def.params.len() == 3
            && matches!(
                class_def.name,
                "Add" | "Subtract" | "Multiply" | "Divide" | "Mod"
            ) {
            let b_to_c = ctx.alloc(MonoType::Fn(gen_tys[1], gen_tys[2]));
            ctx.alloc(MonoType::Fn(gen_tys[0], b_to_c))
        } else if class_def.params.len() == 2
            && matches!(class_def.name, "Eq" | "Compare" | "LessThan")
        {
            let b_to_bool = ctx.alloc(MonoType::Fn(
                gen_tys[1],
                ctx.alloc(MonoType::Prim(Prim::Bool)),
            ));
            ctx.alloc(MonoType::Fn(gen_tys[0], b_to_bool))
        } else {
            lower_type_expr(ctx, &member.ty.ty, &var_map)
        };

        let cst_ty = ctx.alloc(MonoType::Constraint(class_def.name, gen_slice, inner_fn));
        base_env.insert(op_name, cst_ty);
        if op_name != member.name {
            base_env.insert(member.name, cst_ty);
        }
    }
}

fn load_instance_def<'ctx>(
    ctx: &'ctx TypeContext,
    inst_def: &calvin_parse::ast::InstanceDef<'ctx>,
    registry: &mut TypeClassRegistry<'ctx>,
    fn_defs: &mut HashMap<String, &'ctx Expr<'ctx>>,
) {
    let var_map = HashMap::new();
    let mut ground_tys = Vec::new();
    for te in &inst_def.types {
        let mty = lower_type_expr(ctx, te, &var_map);
        ground_tys.push(mty);
    }
    registry.register_instance(inst_def.class_name, ground_tys, Vec::new(), HashMap::new());
    for vd in &inst_def.members {
        let fn_expr = curry_fn(ctx, &vd.args, vd.body);
        let op_name = strip_parens(vd.name);
        if inst_def.class_name != "Convert" {
            fn_defs.insert(op_name.to_string(), fn_expr);
            if op_name != vd.name {
                fn_defs.insert(vd.name.to_string(), fn_expr);
            }
        }
    }
}

fn load_var_type_def<'ctx>(
    ctx: &'ctx TypeContext,
    vtd: &VarTypeDef<'ctx>,
    base_env: &mut TypeEnv<'ctx>,
) {
    let (final_ty, var_name) = lower_var_type_def(ctx, vtd);
    base_env.insert(var_name, final_ty);
    if var_name != vtd.name {
        base_env.insert(vtd.name, final_ty);
    }
}

fn load_var_def<'ctx>(
    ctx: &'ctx TypeContext,
    vd: &calvin_parse::ast::VarDef<'ctx>,
    fn_defs: &mut HashMap<String, &'ctx Expr<'ctx>>,
) {
    let fn_expr = curry_fn(ctx, &vd.args, vd.body);
    let op_name = strip_parens(vd.name);
    fn_defs.insert(op_name.to_string(), fn_expr);
    if op_name != vd.name {
        fn_defs.insert(vd.name.to_string(), fn_expr);
    }
}

fn lower_var_type_def<'ctx>(
    ctx: &'ctx TypeContext,
    var_type_def: &VarTypeDef<'ctx>,
) -> (&'ctx MonoType<'ctx>, &'ctx str) {
    let mut type_vars = Vec::new();
    collect_type_vars(&var_type_def.ty.ty, &mut type_vars);
    for constraint in &var_type_def.ty.context {
        if let calvin_parse::ast::TypeConstraint::Class(_, constraint_args) = constraint {
            for arg in constraint_args {
                collect_type_vars(arg, &mut type_vars);
            }
        }
    }
    let mut var_map = HashMap::new();
    for (i, v) in type_vars.iter().enumerate() {
        var_map.insert(*v, &*ctx.alloc(MonoType::TGen(i)));
    }

    let inner_ty = lower_type_expr(ctx, &var_type_def.ty.ty, &var_map);
    let mut final_ty = inner_ty;
    for constraint in var_type_def.ty.context.iter().rev() {
        if let calvin_parse::ast::TypeConstraint::Class(class_name, constraint_args) = constraint {
            let carg_tys: Vec<&'ctx MonoType<'ctx>> = constraint_args
                .iter()
                .map(|arg| lower_type_expr(ctx, arg, &var_map))
                .collect();
            let carg_slice = ctx.arena().alloc_slice_clone(&carg_tys);
            final_ty = ctx.alloc(MonoType::Constraint(class_name, carg_slice, final_ty));
        }
    }

    let var_name = strip_parens(var_type_def.name);
    (final_ty, var_name)
}

fn collect_type_vars<'a>(type_expr: &TypeExpr<'a>, vars: &mut Vec<&'a str>) {
    match type_expr {
        TypeExpr::Var(var_name) => {
            if !vars.contains(var_name) {
                vars.push(var_name);
            }
        }
        TypeExpr::Prim(_) => {}
        TypeExpr::Tuple(elem_types) => {
            for elem_type in elem_types {
                collect_type_vars(elem_type, vars);
            }
        }
        TypeExpr::Fn(domain, codomain) => {
            collect_type_vars(domain, vars);
            collect_type_vars(codomain, vars);
        }
        TypeExpr::Array(element_type) => {
            collect_type_vars(element_type, vars);
        }
        TypeExpr::App(head, type_args) => {
            collect_type_vars(head, vars);
            for arg in type_args {
                collect_type_vars(arg, vars);
            }
        }
    }
}

fn lower_type_expr<'a, 'ctx>(
    ctx: &'ctx TypeContext,
    type_expr: &TypeExpr<'a>,
    var_map: &HashMap<&'a str, &'ctx MonoType<'ctx>>,
) -> &'ctx MonoType<'ctx> {
    match type_expr {
        TypeExpr::Prim(prim) => ctx.alloc(MonoType::Prim(*prim)),
        TypeExpr::Var(var_name) => {
            if let Some(&mono_ty) = var_map.get(var_name) {
                mono_ty
            } else {
                ctx.alloc(MonoType::TVar(
                    ctx.fresh_tvar_id(),
                    std::cell::Cell::new(None),
                ))
            }
        }
        TypeExpr::Tuple(elem_types) => {
            let lowered: Vec<&'ctx MonoType<'ctx>> = elem_types
                .iter()
                .map(|elem| lower_type_expr(ctx, elem, var_map))
                .collect();
            ctx.alloc(MonoType::Tuple(ctx.arena().alloc_slice_clone(&lowered)))
        }
        TypeExpr::Fn(domain, codomain) => {
            let lowered_domain = lower_type_expr(ctx, domain, var_map);
            let lowered_codomain = lower_type_expr(ctx, codomain, var_map);
            ctx.alloc(MonoType::Fn(lowered_domain, lowered_codomain))
        }
        TypeExpr::Array(element_type) => {
            let lowered_elem = lower_type_expr(ctx, element_type, var_map);
            ctx.alloc(MonoType::Array(lowered_elem))
        }
        TypeExpr::App(head, type_args) => {
            let lowered_head = lower_type_expr(ctx, head, var_map);
            let lowered_args: Vec<&'ctx MonoType<'ctx>> = type_args
                .iter()
                .map(|arg| lower_type_expr(ctx, arg, var_map))
                .collect();
            ctx.alloc(MonoType::App(
                lowered_head,
                ctx.arena().alloc_slice_clone(&lowered_args),
            ))
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use calvin_core::lang::expr::ExprVisitor;

    #[test]
    fn test_bootstrap_arith() {
        let ctx = TypeContext::new();
        let (env, registry) = init_bootstrap(&ctx).expect("bootstrap failed");

        assert!(env.lookup("+").is_some());
        assert!(env.lookup("-").is_some());
        assert!(env.lookup("*").is_some());
        assert!(env.lookup("/").is_some());

        assert!(registry.classes.contains_key("Add"));
        assert!(registry.classes.contains_key("Subtract"));
        assert!(registry.classes.contains_key("Multiply"));
        assert!(registry.classes.contains_key("Divide"));

        let add_insts = registry
            .instances
            .get("Add")
            .expect("Add instances missing");
        assert!(!add_insts.is_empty());
    }

    #[test]
    fn test_bootstrap_to_lower() {
        let ctx = TypeContext::new();
        let (env, registry) = init_bootstrap(&ctx).expect("bootstrap failed");

        let to_lower_ty = env.lookup("toLower").expect("toLower must be bound in env");
        let formatted = calvin_core::lang::types::format_mono(to_lower_ty, &HashMap::new());
        assert_eq!(formatted, "(char) -> char");

        let to_upper_ty = env.lookup("toUpper").expect("toUpper must be bound in env");
        let formatted_upper = calvin_core::lang::types::format_mono(to_upper_ty, &HashMap::new());
        assert_eq!(formatted_upper, "(char) -> char");

        // Type inference on :t toLower
        let mut typeinf = calvin_core::lang::typeinf::TypeInference::with_env_and_classes(
            &ctx,
            env.clone(),
            registry.clone(),
        );
        let ast = calvin_parse::parse_expr(&ctx, "toLower").expect("parse failed");
        let ty = typeinf.visit(ast).expect("infer failed");
        typeinf.solve_constraints().expect("solve failed");
        let residuals = typeinf.residual_constraints();
        let result = calvin_core::lang::types::format_qual_type(ty, &residuals);
        assert_eq!(result, "(char) -> char");

        let (_env, _registry, fn_defs) = init_bootstrap_with_defs(&ctx).expect("bootstrap failed");
        assert!(fn_defs.contains_key("toLower"));
        assert!(fn_defs.contains_key("toUpper"));
    }

    #[test]
    fn test_hobbes_bootstrap_type_inference() {
        let ctx = TypeContext::new();
        let (env, registry) = init_bootstrap(&ctx).expect("bootstrap failed");

        let mut typeinf = calvin_core::lang::typeinf::TypeInference::with_env_and_classes(
            &ctx,
            env.clone(),
            registry.clone(),
        );

        // 1. :t (\x y. x + y) (1.0, 2.0)
        let ast1 =
            calvin_parse::parse_expr(&ctx, r"(\x y. x + y) (1.0, 2.0)").expect("parse failed");
        let ty1 = typeinf.visit(ast1).expect("infer failed");
        typeinf.solve_constraints().expect("solve failed");
        let residuals1 = typeinf.residual_constraints();
        let formatted1 = calvin_core::lang::types::format_qual_type(ty1, &residuals1);
        assert_eq!(formatted1, "double");

        // 2. :t (\x -> \y -> x + y) 1.0 2.0
        let mut typeinf2 = calvin_core::lang::typeinf::TypeInference::with_env_and_classes(
            &ctx,
            env.clone(),
            registry.clone(),
        );
        let ast2 =
            calvin_parse::parse_expr(&ctx, r"(\x -> \y -> x + y) 1.0 2.0").expect("parse failed");
        let ty2 = typeinf2.visit(ast2).expect("infer failed");
        typeinf2.solve_constraints().expect("solve failed");
        let residuals2 = typeinf2.residual_constraints();
        let formatted2 = calvin_core::lang::types::format_qual_type(ty2, &residuals2);
        assert_eq!(formatted2, "double");
    }

    #[test]
    fn test_bootstrap_array_index_from() {
        let ctx = TypeContext::new();
        let (env, registry) = init_bootstrap(&ctx).expect("bootstrap failed");

        assert!(registry.classes.contains_key("ArrayIndex"));
        let instances = registry
            .instances
            .get("ArrayIndex")
            .expect("ArrayIndex instances missing");
        assert_eq!(instances.len(), 4);

        let mut typeinf = calvin_core::lang::typeinf::TypeInference::with_env_and_classes(
            &ctx,
            env.clone(),
            registry.clone(),
        );
        let ast = calvin_parse::parse_expr(&ctx, "arrayIndexFrom").expect("parse failed");
        let ty = typeinf.visit(ast).expect("infer failed");
        typeinf.solve_constraints().expect("solve failed");
        let residuals = typeinf.residual_constraints();
        let formatted = calvin_core::lang::types::format_qual_type(ty, &residuals);
        assert_eq!(formatted, "ArrayIndex a => (a) -> long");

        // Application to concrete int literal: arrayIndexFrom 42
        let mut typeinf2 = calvin_core::lang::typeinf::TypeInference::with_env_and_classes(
            &ctx,
            env.clone(),
            registry.clone(),
        );
        let ast2 = calvin_parse::parse_expr(&ctx, "arrayIndexFrom 42").expect("parse failed");
        let ty2 = typeinf2.visit(ast2).expect("infer failed");
        typeinf2.solve_constraints().expect("solve failed");
        let residuals2 = typeinf2.residual_constraints();
        let formatted2 = calvin_core::lang::types::format_qual_type(ty2, &residuals2);
        assert_eq!(formatted2, "long");
    }

    #[test]
    fn test_bootstrap_convert() {
        let ctx = TypeContext::new();
        let (env, registry) = init_bootstrap(&ctx).expect("bootstrap failed");

        assert!(registry.classes.contains_key("Convert"));
        let instances = registry
            .instances
            .get("Convert")
            .expect("Convert instances missing");
        assert!(!instances.is_empty());

        let mut typeinf = calvin_core::lang::typeinf::TypeInference::with_env_and_classes(
            &ctx,
            env.clone(),
            registry.clone(),
        );
        let ast = calvin_parse::parse_expr(&ctx, "convert").expect("parse failed");
        let ty = typeinf.visit(ast).expect("infer failed");
        typeinf.solve_constraints().expect("solve failed");
        let residuals = typeinf.residual_constraints();
        let formatted = calvin_core::lang::types::format_qual_type(ty, &residuals);
        assert_eq!(formatted, "Convert a b => (a) -> b");
    }

    #[test]
    fn test_boot_environment_aggregate() {
        let ctx = TypeContext::new();
        let boot_env = init_boot_environment(&ctx).expect("init boot env failed");

        assert!(boot_env.env().lookup("+").is_some());
        assert!(boot_env.registry().classes.contains_key("Add"));
        assert!(boot_env.fn_def("toLower").is_some());
    }
}
