use calvin_core::context::TypeContext;
use calvin_core::lang::typeclass::TypeClassRegistry;
use calvin_core::lang::typeinf::TypeEnv;
use calvin_core::lang::types::{MonoType, Prim};
use calvin_parse::ast::{ModuleDef, TypeExpr, VarTypeDef};
use calvin_parse::parse_module;
use std::collections::HashMap;
use std::rc::Rc;

// Generated by build.rs: embeds all boot/*.hob scripts in alphabetical order
include!(concat!(env!("OUT_DIR"), "/boot_scripts.rs"));

pub fn boot_script(name: &str) -> Option<&'static str> {
    BOOT_SCRIPTS
        .iter()
        .find(|(n, _)| *n == name)
        .map(|(_, content)| *content)
}

fn init_builtin_env<'ctx>(ctx: &'ctx TypeContext, base_env: &mut TypeEnv<'ctx>) {
    let bool_ty: &'ctx MonoType<'ctx> = &*ctx.alloc(MonoType::Prim(Prim::Bool));
    let tup = ctx.alloc(MonoType::Tuple(ctx.arena().alloc_slice_clone(&[bool_ty, bool_ty])));
    let tup_to_bool = ctx.alloc(MonoType::Fn(tup, bool_ty));
    let bool_to_bool = ctx.alloc(MonoType::Fn(bool_ty, bool_ty));

    base_env.insert("and", tup_to_bool);
    base_env.insert("or", tup_to_bool);
    base_env.insert("not", bool_to_bool);
}

pub fn init_bootstrap<'ctx>(
    ctx: &'ctx TypeContext,
) -> Result<(Rc<TypeEnv<'ctx>>, Rc<TypeClassRegistry<'ctx>>), String> {
    let mut base_env = TypeEnv::new();
    let mut registry = TypeClassRegistry::new();

    // 0. Initialize built-in macro/std functions matching Hobbes
    init_builtin_env(ctx, &mut base_env);

    // 1. Process all boot scripts in alphabetical order
    for (_name, content) in BOOT_SCRIPTS {
        if let Ok(module) = parse_module(ctx, content) {
            load_module_defs(ctx, &module.defs, &mut base_env, &mut registry);
        }
    }

    Ok((Rc::new(base_env), Rc::new(registry)))
}

fn load_module_defs<'ctx>(
    ctx: &'ctx TypeContext,
    defs: &[ModuleDef<'ctx>],
    base_env: &mut TypeEnv<'ctx>,
    registry: &mut TypeClassRegistry<'ctx>,
) {
    for def in defs {
        match def {
            ModuleDef::Class(class_def) => {
                let mut fundeps = Vec::new();
                for (from_names, to_names) in &class_def.fundeps {
                    let from_indices: Vec<usize> = from_names
                        .iter()
                        .filter_map(|name| class_def.params.iter().position(|p| p == name))
                        .collect();
                    let to_indices: Vec<usize> = to_names
                        .iter()
                        .filter_map(|name| class_def.params.iter().position(|p| p == name))
                        .collect();
                    fundeps.push((from_indices, to_indices));
                }

                // Register class into registry
                registry.register_class(
                    class_def.name,
                    class_def.params.clone(),
                    fundeps,
                    HashMap::new(),
                );

                // Build type parameters as TGen(0), TGen(1), ...
                let mut var_map = HashMap::new();
                let gen_tys: Vec<&'ctx MonoType<'ctx>> = (0..class_def.params.len())
                    .map(|i| {
                        let g = &*ctx.alloc(MonoType::TGen(i));
                        var_map.insert(class_def.params[i], g);
                        g
                    })
                    .collect();
                let gen_slice = ctx.arena().alloc_slice_clone(&gen_tys);

                // For each member, bind its qualified constraint type in base_env
                for member in &class_def.members {
                    let mut op_name = member.name;
                    if op_name.starts_with('(') && op_name.ends_with(')') && op_name.len() >= 3 {
                        op_name = &op_name[1..op_name.len() - 1];
                    }

                    let inner_fn = if class_def.params.len() == 3 {
                        let b_to_c = ctx.alloc(MonoType::Fn(gen_tys[1], gen_tys[2]));
                        ctx.alloc(MonoType::Fn(gen_tys[0], b_to_c))
                    } else if class_def.params.len() == 1 {
                        if op_name == "neg" {
                            ctx.alloc(MonoType::Fn(gen_tys[0], gen_tys[0]))
                        } else {
                            gen_tys[0]
                        }
                    } else if class_def.params.len() == 2 {
                        let b_to_bool = ctx.alloc(MonoType::Fn(gen_tys[1], ctx.alloc(MonoType::Prim(Prim::Bool))));
                        ctx.alloc(MonoType::Fn(gen_tys[0], b_to_bool))
                    } else {
                        lower_type_expr(ctx, &member.ty.ty, &var_map)
                    };

                    let cst_ty = ctx.alloc(MonoType::Constraint(class_def.name, gen_slice, inner_fn));
                    base_env.insert(op_name, cst_ty);
                    if op_name != member.name {
                        base_env.insert(member.name, cst_ty);
                    }
                }
            }
            ModuleDef::Instance(inst_def) => {
                let var_map = HashMap::new();
                let mut ground_tys = Vec::new();
                for te in &inst_def.types {
                    let mty = lower_type_expr(ctx, te, &var_map);
                    ground_tys.push(mty);
                }
                registry.register_instance(
                    inst_def.class_name,
                    ground_tys,
                    Vec::new(),
                    HashMap::new(),
                );
            }
            ModuleDef::VarType(vtd) => {
                let (final_ty, var_name) = lower_var_type_def(ctx, vtd);
                base_env.insert(var_name, final_ty);
                if var_name != vtd.name {
                    base_env.insert(vtd.name, final_ty);
                }
            }
            ModuleDef::VarDef(_) => {}
        }
    }
}

fn lower_var_type_def<'ctx>(
    ctx: &'ctx TypeContext,
    vtd: &VarTypeDef<'ctx>,
) -> (&'ctx MonoType<'ctx>, &'ctx str) {
    let mut type_vars = Vec::new();
    collect_type_vars(&vtd.ty.ty, &mut type_vars);
    for c in &vtd.ty.context {
        if let calvin_parse::ast::TypeConstraint::Class(_, cargs) = c {
            for a in cargs {
                collect_type_vars(a, &mut type_vars);
            }
        }
    }
    let mut var_map = HashMap::new();
    for (i, v) in type_vars.iter().enumerate() {
        var_map.insert(*v, &*ctx.alloc(MonoType::TGen(i)));
    }

    let inner_ty = lower_type_expr(ctx, &vtd.ty.ty, &var_map);
    let mut final_ty = inner_ty;
    for c in vtd.ty.context.iter().rev() {
        if let calvin_parse::ast::TypeConstraint::Class(cname, cargs) = c {
            let carg_tys: Vec<&'ctx MonoType<'ctx>> = cargs
                .iter()
                .map(|a| lower_type_expr(ctx, a, &var_map))
                .collect();
            let carg_slice = ctx.arena().alloc_slice_clone(&carg_tys);
            final_ty = ctx.alloc(MonoType::Constraint(cname, carg_slice, final_ty));
        }
    }

    let mut var_name = vtd.name;
    if var_name.starts_with('(') && var_name.ends_with(')') && var_name.len() >= 3 {
        var_name = &var_name[1..var_name.len() - 1];
    }
    (final_ty, var_name)
}

fn collect_type_vars<'a>(te: &TypeExpr<'a>, vars: &mut Vec<&'a str>) {
    match te {
        TypeExpr::Var(v) => {
            if !vars.contains(v) {
                vars.push(v);
            }
        }
        TypeExpr::Prim(_) => {}
        TypeExpr::Tuple(ts) => {
            for t in ts {
                collect_type_vars(t, vars);
            }
        }
        TypeExpr::Fn(dom, codom) => {
            collect_type_vars(dom, vars);
            collect_type_vars(codom, vars);
        }
        TypeExpr::Array(inner) => {
            collect_type_vars(inner, vars);
        }
    }
}

fn lower_type_expr<'a, 'ctx>(
    ctx: &'ctx TypeContext,
    te: &TypeExpr<'a>,
    var_map: &HashMap<&'a str, &'ctx MonoType<'ctx>>,
) -> &'ctx MonoType<'ctx> {
    match te {
        TypeExpr::Prim(p) => ctx.alloc(MonoType::Prim(*p)),
        TypeExpr::Var(v) => {
            if let Some(mty) = var_map.get(v) {
                *mty
            } else {
                ctx.alloc(MonoType::TVar(ctx.fresh_tvar_id(), std::cell::Cell::new(None)))
            }
        }
        TypeExpr::Tuple(ts) => {
            let lowered: Vec<&'ctx MonoType<'ctx>> = ts.iter().map(|t| lower_type_expr(ctx, t, var_map)).collect();
            ctx.alloc(MonoType::Tuple(ctx.arena().alloc_slice_clone(&lowered)))
        }
        TypeExpr::Fn(dom, codom) => {
            let d = lower_type_expr(ctx, dom, var_map);
            let c = lower_type_expr(ctx, codom, var_map);
            ctx.alloc(MonoType::Fn(d, c))
        }
        TypeExpr::Array(inner) => {
            let elem = lower_type_expr(ctx, inner, var_map);
            ctx.alloc(MonoType::Array(elem))
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use calvin_core::lang::expr::ExprVisitor;

    #[test]
    fn test_bootstrap_arith() {
        let ctx = TypeContext::new();
        let (env, registry) = init_bootstrap(&ctx).expect("bootstrap failed");

        assert!(env.lookup("+").is_some());
        assert!(env.lookup("-").is_some());
        assert!(env.lookup("*").is_some());
        assert!(env.lookup("/").is_some());

        assert!(registry.classes.contains_key("Add"));
        assert!(registry.classes.contains_key("Subtract"));
        assert!(registry.classes.contains_key("Multiply"));
        assert!(registry.classes.contains_key("Divide"));

        let add_insts = registry.instances.get("Add").expect("Add instances missing");
        assert!(!add_insts.is_empty());
    }

    #[test]
    fn test_bootstrap_to_lower() {
        let ctx = TypeContext::new();
        let (env, registry) = init_bootstrap(&ctx).expect("bootstrap failed");

        let to_lower_ty = env.lookup("toLower").expect("toLower must be bound in env");
        let formatted = calvin_core::lang::types::format_mono(to_lower_ty, &HashMap::new());
        assert_eq!(formatted, "(char) -> char");

        let to_upper_ty = env.lookup("toUpper").expect("toUpper must be bound in env");
        let formatted_upper = calvin_core::lang::types::format_mono(to_upper_ty, &HashMap::new());
        assert_eq!(formatted_upper, "(char) -> char");

        // Type inference on :t toLower
        let mut typeinf = calvin_core::lang::typeinf::TypeInference::with_env_and_classes(
            &ctx,
            env.clone(),
            registry.clone(),
        );
        let ast = calvin_parse::parse_expr(&ctx, "toLower").expect("parse failed");
        let ty = typeinf.visit(ast).expect("infer failed");
        typeinf.solve_constraints().expect("solve failed");
        let residuals = typeinf.residual_constraints();
        let result = calvin_core::lang::types::format_qual_type(ty, &residuals);
        assert_eq!(result, "(char) -> char");
    }

    #[test]
    fn test_hobbes_bootstrap_type_inference() {
        let ctx = TypeContext::new();
        let (env, registry) = init_bootstrap(&ctx).expect("bootstrap failed");

        let mut typeinf = calvin_core::lang::typeinf::TypeInference::with_env_and_classes(
            &ctx,
            env.clone(),
            registry.clone(),
        );

        // 1. :t (\x y. x + y) (1.0, 2.0)
        let ast1 = calvin_parse::parse_expr(&ctx, r"(\x y. x + y) (1.0, 2.0)").expect("parse failed");
        let ty1 = typeinf.visit(ast1).expect("infer failed");
        typeinf.solve_constraints().expect("solve failed");
        let residuals1 = typeinf.residual_constraints();
        let formatted1 = calvin_core::lang::types::format_qual_type(ty1, &residuals1);
        assert_eq!(formatted1, "double");

        // 2. :t (\x -> \y -> x + y) 1.0 2.0
        let mut typeinf2 = calvin_core::lang::typeinf::TypeInference::with_env_and_classes(
            &ctx,
            env.clone(),
            registry.clone(),
        );
        let ast2 = calvin_parse::parse_expr(&ctx, r"(\x -> \y -> x + y) 1.0 2.0").expect("parse failed");
        let ty2 = typeinf2.visit(ast2).expect("infer failed");
        typeinf2.solve_constraints().expect("solve failed");
        let residuals2 = typeinf2.residual_constraints();
        let formatted2 = calvin_core::lang::types::format_qual_type(ty2, &residuals2);
        assert_eq!(formatted2, "double");
    }
}
