use calvin_core::context::TypeContext;
use calvin_core::lang::expr::{Expr, Pattern};
use calvin_core::lang::typeclass::TypeClassRegistry;
use calvin_core::lang::typeinf::TypeEnv;
use calvin_core::lang::types::{MonoType, Prim};
use calvin_parse::ast::{ModuleDef, TypeExpr, VarTypeDef};
use calvin_parse::parse_module;
use std::collections::HashMap;
use std::rc::Rc;

// Generated by build.rs: embeds all boot/*.hob scripts in alphabetical order
include!(concat!(env!("OUT_DIR"), "/boot_scripts.rs"));

pub fn boot_script(name: &str) -> Option<&'static str> {
    BOOT_SCRIPTS
        .iter()
        .find(|(n, _)| *n == name)
        .map(|(_, content)| *content)
}

fn init_builtin_env<'ctx>(
    ctx: &'ctx TypeContext,
    base_env: &mut TypeEnv<'ctx>,
    registry: &mut TypeClassRegistry<'ctx>,
) {
    let bool_ty: &'ctx MonoType<'ctx> = &*ctx.alloc(MonoType::Prim(Prim::Bool));
    let tup = ctx.alloc(MonoType::Tuple(ctx.arena().alloc_slice_clone(&[bool_ty, bool_ty])));
    let tup_to_bool = ctx.alloc(MonoType::Fn(tup, bool_ty));
    let bool_to_bool = ctx.alloc(MonoType::Fn(bool_ty, bool_ty));

    base_env.insert("and", tup_to_bool);
    base_env.insert("or", tup_to_bool);
    base_env.insert("not", bool_to_bool);

    // Identity and conversion primitives matching Hobbes
    let tgen0: &'ctx MonoType<'ctx> = &*ctx.alloc(MonoType::TGen(0));
    let tgen1: &'ctx MonoType<'ctx> = &*ctx.alloc(MonoType::TGen(1));
    base_env.insert("id", ctx.alloc(MonoType::Fn(tgen0, tgen0)));

    let int_ty: &'ctx MonoType<'ctx> = &*ctx.alloc(MonoType::Prim(Prim::Int));
    let long_ty: &'ctx MonoType<'ctx> = &*ctx.alloc(MonoType::Prim(Prim::Long));
    let short_ty: &'ctx MonoType<'ctx> = &*ctx.alloc(MonoType::Prim(Prim::Short));
    let byte_ty: &'ctx MonoType<'ctx> = &*ctx.alloc(MonoType::Prim(Prim::Byte));
    let float_ty: &'ctx MonoType<'ctx> = &*ctx.alloc(MonoType::Prim(Prim::Float));
    let double_ty: &'ctx MonoType<'ctx> = &*ctx.alloc(MonoType::Prim(Prim::Double));
    let int128_ty: &'ctx MonoType<'ctx> = &*ctx.alloc(MonoType::Prim(Prim::Int128));

    base_env.insert("b2i", ctx.alloc(MonoType::Fn(byte_ty, int_ty)));
    base_env.insert("b2l", ctx.alloc(MonoType::Fn(byte_ty, long_ty)));
    base_env.insert("s2i", ctx.alloc(MonoType::Fn(short_ty, int_ty)));
    base_env.insert("i2l", ctx.alloc(MonoType::Fn(int_ty, long_ty)));
    base_env.insert("i2d", ctx.alloc(MonoType::Fn(int_ty, double_ty)));
    base_env.insert("i2f", ctx.alloc(MonoType::Fn(int_ty, float_ty)));
    base_env.insert("l2d", ctx.alloc(MonoType::Fn(long_ty, double_ty)));
    base_env.insert("l2f", ctx.alloc(MonoType::Fn(long_ty, float_ty)));
    base_env.insert("f2d", ctx.alloc(MonoType::Fn(float_ty, double_ty)));
    base_env.insert("l2i16", ctx.alloc(MonoType::Fn(long_ty, int128_ty)));

    // Hobbes builtin primitive type class: Convert a b => (a) -> b
    registry.register_class(
        "Convert",
        vec!["a", "b"],
        Vec::new(),
        HashMap::new(),
    );

    let gen_slice = ctx.arena().alloc_slice_clone(&[tgen0, tgen1]);
    let a_to_b = ctx.alloc(MonoType::Fn(tgen0, tgen1));
    let convert_cst_ty = ctx.alloc(MonoType::Constraint("Convert", gen_slice, a_to_b));
    base_env.insert("convert", convert_cst_ty);
}

pub fn init_bootstrap_with_defs<'ctx>(
    ctx: &'ctx TypeContext,
) -> Result<(Rc<TypeEnv<'ctx>>, Rc<TypeClassRegistry<'ctx>>, Rc<HashMap<String, &'ctx Expr<'ctx>>>), String> {
    let mut base_env = TypeEnv::new();
    let mut registry = TypeClassRegistry::new();
    let mut fn_defs = HashMap::new();

    // 0. Initialize built-in macro/std functions matching Hobbes
    init_builtin_env(ctx, &mut base_env, &mut registry);

    let id_fn = &*ctx.alloc(Expr::Fn(Pattern::Var("x"), ctx.alloc(Expr::Var("x"))));
    fn_defs.insert("id".to_string(), id_fn);
    fn_defs.insert("convert".to_string(), id_fn);
    fn_defs.insert("b2i".to_string(), id_fn);
    fn_defs.insert("b2l".to_string(), id_fn);
    fn_defs.insert("s2i".to_string(), id_fn);
    fn_defs.insert("i2l".to_string(), id_fn);
    fn_defs.insert("i2d".to_string(), id_fn);
    fn_defs.insert("i2f".to_string(), id_fn);
    fn_defs.insert("l2d".to_string(), id_fn);
    fn_defs.insert("l2f".to_string(), id_fn);
    fn_defs.insert("f2d".to_string(), id_fn);
    fn_defs.insert("l2i16".to_string(), id_fn);

    // 1. Process all boot scripts in alphabetical order
    for (_name, content) in BOOT_SCRIPTS {
        if let Ok(module) = parse_module(ctx, content) {
            load_module_defs(ctx, &module.defs, &mut base_env, &mut registry, &mut fn_defs);
        }
    }

    Ok((Rc::new(base_env), Rc::new(registry), Rc::new(fn_defs)))
}

pub fn init_bootstrap<'ctx>(
    ctx: &'ctx TypeContext,
) -> Result<(Rc<TypeEnv<'ctx>>, Rc<TypeClassRegistry<'ctx>>), String> {
    let (env, reg, _) = init_bootstrap_with_defs(ctx)?;
    Ok((env, reg))
}

fn load_module_defs<'ctx>(
    ctx: &'ctx TypeContext,
    defs: &[ModuleDef<'ctx>],
    base_env: &mut TypeEnv<'ctx>,
    registry: &mut TypeClassRegistry<'ctx>,
    fn_defs: &mut HashMap<String, &'ctx Expr<'ctx>>,
) {
    for def in defs {
        match def {
            ModuleDef::Class(class_def) => {
                let mut fundeps = Vec::new();
                for (from_names, to_names) in &class_def.fundeps {
                    let from_indices: Vec<usize> = from_names
                        .iter()
                        .filter_map(|name| class_def.params.iter().position(|p| p == name))
                        .collect();
                    let to_indices: Vec<usize> = to_names
                        .iter()
                        .filter_map(|name| class_def.params.iter().position(|p| p == name))
                        .collect();
                    fundeps.push((from_indices, to_indices));
                }

                // Register class into registry
                registry.register_class(
                    class_def.name,
                    class_def.params.clone(),
                    fundeps,
                    HashMap::new(),
                );

                // Build type parameters as TGen(0), TGen(1), ...
                let mut var_map = HashMap::new();
                let gen_tys: Vec<&'ctx MonoType<'ctx>> = (0..class_def.params.len())
                    .map(|i| {
                        let g = &*ctx.alloc(MonoType::TGen(i));
                        var_map.insert(class_def.params[i], g);
                        g
                    })
                    .collect();
                let gen_slice = ctx.arena().alloc_slice_clone(&gen_tys);

                // For each member, bind its qualified constraint type in base_env
                for member in &class_def.members {
                    let mut op_name = member.name;
                    if op_name.starts_with('(') && op_name.ends_with(')') && op_name.len() >= 3 {
                        op_name = &op_name[1..op_name.len() - 1];
                    }

                    let inner_fn = if class_def.params.len() == 3 && matches!(class_def.name, "Add" | "Subtract" | "Multiply" | "Divide" | "Mod") {
                        let b_to_c = ctx.alloc(MonoType::Fn(gen_tys[1], gen_tys[2]));
                        ctx.alloc(MonoType::Fn(gen_tys[0], b_to_c))
                    } else if class_def.params.len() == 2 && matches!(class_def.name, "Eq" | "Compare" | "LessThan") {
                        let b_to_bool = ctx.alloc(MonoType::Fn(gen_tys[1], ctx.alloc(MonoType::Prim(Prim::Bool))));
                        ctx.alloc(MonoType::Fn(gen_tys[0], b_to_bool))
                    } else {
                        lower_type_expr(ctx, &member.ty.ty, &var_map)
                    };

                    let cst_ty = ctx.alloc(MonoType::Constraint(class_def.name, gen_slice, inner_fn));
                    base_env.insert(op_name, cst_ty);
                    if op_name != member.name {
                        base_env.insert(member.name, cst_ty);
                    }
                }
            }
            ModuleDef::Instance(inst_def) => {
                let var_map = HashMap::new();
                let mut ground_tys = Vec::new();
                for te in &inst_def.types {
                    let mty = lower_type_expr(ctx, te, &var_map);
                    ground_tys.push(mty);
                }
                registry.register_instance(
                    inst_def.class_name,
                    ground_tys,
                    Vec::new(),
                    HashMap::new(),
                );
                for vd in &inst_def.members {
                    let fn_expr = if vd.args.is_empty() {
                        vd.body
                    } else {
                        vd.args.iter().rev().fold(vd.body, |acc, arg| {
                            &*ctx.alloc(Expr::Fn(Pattern::Var(arg), acc))
                        })
                    };
                    let mut op_name = vd.name;
                    if op_name.starts_with('(') && op_name.ends_with(')') && op_name.len() >= 3 {
                        op_name = &op_name[1..op_name.len() - 1];
                    }
                    fn_defs.insert(op_name.to_string(), fn_expr);
                    if op_name != vd.name {
                        fn_defs.insert(vd.name.to_string(), fn_expr);
                    }
                }
            }
            ModuleDef::VarType(vtd) => {
                let (final_ty, var_name) = lower_var_type_def(ctx, vtd);
                base_env.insert(var_name, final_ty);
                if var_name != vtd.name {
                    base_env.insert(vtd.name, final_ty);
                }
            }
            ModuleDef::VarDef(vd) => {
                let fn_expr = if vd.args.is_empty() {
                    vd.body
                } else {
                    vd.args.iter().rev().fold(vd.body, |acc, arg| {
                        &*ctx.alloc(Expr::Fn(Pattern::Var(arg), acc))
                    })
                };
                let mut op_name = vd.name;
                if op_name.starts_with('(') && op_name.ends_with(')') && op_name.len() >= 3 {
                    op_name = &op_name[1..op_name.len() - 1];
                }
                fn_defs.insert(op_name.to_string(), fn_expr);
                if op_name != vd.name {
                    fn_defs.insert(vd.name.to_string(), fn_expr);
                }
            }
            ModuleDef::Data(_) => {
                // Type alias / data vector definitions in boot scripts
            }
        }
    }
}

fn lower_var_type_def<'ctx>(
    ctx: &'ctx TypeContext,
    vtd: &VarTypeDef<'ctx>,
) -> (&'ctx MonoType<'ctx>, &'ctx str) {
    let mut type_vars = Vec::new();
    collect_type_vars(&vtd.ty.ty, &mut type_vars);
    for c in &vtd.ty.context {
        if let calvin_parse::ast::TypeConstraint::Class(_, cargs) = c {
            for a in cargs {
                collect_type_vars(a, &mut type_vars);
            }
        }
    }
    let mut var_map = HashMap::new();
    for (i, v) in type_vars.iter().enumerate() {
        var_map.insert(*v, &*ctx.alloc(MonoType::TGen(i)));
    }

    let inner_ty = lower_type_expr(ctx, &vtd.ty.ty, &var_map);
    let mut final_ty = inner_ty;
    for c in vtd.ty.context.iter().rev() {
        if let calvin_parse::ast::TypeConstraint::Class(cname, cargs) = c {
            let carg_tys: Vec<&'ctx MonoType<'ctx>> = cargs
                .iter()
                .map(|a| lower_type_expr(ctx, a, &var_map))
                .collect();
            let carg_slice = ctx.arena().alloc_slice_clone(&carg_tys);
            final_ty = ctx.alloc(MonoType::Constraint(cname, carg_slice, final_ty));
        }
    }

    let mut var_name = vtd.name;
    if var_name.starts_with('(') && var_name.ends_with(')') && var_name.len() >= 3 {
        var_name = &var_name[1..var_name.len() - 1];
    }
    (final_ty, var_name)
}

fn collect_type_vars<'a>(te: &TypeExpr<'a>, vars: &mut Vec<&'a str>) {
    match te {
        TypeExpr::Var(v) => {
            if !vars.contains(v) {
                vars.push(v);
            }
        }
        TypeExpr::Prim(_) => {}
        TypeExpr::Tuple(ts) => {
            for t in ts {
                collect_type_vars(t, vars);
            }
        }
        TypeExpr::Fn(dom, codom) => {
            collect_type_vars(dom, vars);
            collect_type_vars(codom, vars);
        }
        TypeExpr::Array(inner) => {
            collect_type_vars(inner, vars);
        }
        TypeExpr::App(head, args) => {
            collect_type_vars(head, vars);
            for a in args {
                collect_type_vars(a, vars);
            }
        }
    }
}

fn lower_type_expr<'a, 'ctx>(
    ctx: &'ctx TypeContext,
    te: &TypeExpr<'a>,
    var_map: &HashMap<&'a str, &'ctx MonoType<'ctx>>,
) -> &'ctx MonoType<'ctx> {
    match te {
        TypeExpr::Prim(p) => ctx.alloc(MonoType::Prim(*p)),
        TypeExpr::Var(v) => {
            if let Some(mty) = var_map.get(v) {
                *mty
            } else {
                ctx.alloc(MonoType::TVar(ctx.fresh_tvar_id(), std::cell::Cell::new(None)))
            }
        }
        TypeExpr::Tuple(ts) => {
            let lowered: Vec<&'ctx MonoType<'ctx>> = ts.iter().map(|t| lower_type_expr(ctx, t, var_map)).collect();
            ctx.alloc(MonoType::Tuple(ctx.arena().alloc_slice_clone(&lowered)))
        }
        TypeExpr::Fn(dom, codom) => {
            let d = lower_type_expr(ctx, dom, var_map);
            let c = lower_type_expr(ctx, codom, var_map);
            ctx.alloc(MonoType::Fn(d, c))
        }
        TypeExpr::Array(inner) => {
            let elem = lower_type_expr(ctx, inner, var_map);
            ctx.alloc(MonoType::Array(elem))
        }
        TypeExpr::App(head, args) => {
            let h = lower_type_expr(ctx, head, var_map);
            let lowered_args: Vec<&'ctx MonoType<'ctx>> =
                args.iter().map(|a| lower_type_expr(ctx, a, var_map)).collect();
            ctx.alloc(MonoType::App(
                h,
                ctx.arena().alloc_slice_clone(&lowered_args),
            ))
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use calvin_core::lang::expr::ExprVisitor;

    #[test]
    fn test_bootstrap_arith() {
        let ctx = TypeContext::new();
        let (env, registry) = init_bootstrap(&ctx).expect("bootstrap failed");

        assert!(env.lookup("+").is_some());
        assert!(env.lookup("-").is_some());
        assert!(env.lookup("*").is_some());
        assert!(env.lookup("/").is_some());

        assert!(registry.classes.contains_key("Add"));
        assert!(registry.classes.contains_key("Subtract"));
        assert!(registry.classes.contains_key("Multiply"));
        assert!(registry.classes.contains_key("Divide"));

        let add_insts = registry.instances.get("Add").expect("Add instances missing");
        assert!(!add_insts.is_empty());
    }

    #[test]
    fn test_bootstrap_to_lower() {
        let ctx = TypeContext::new();
        let (env, registry) = init_bootstrap(&ctx).expect("bootstrap failed");

        let to_lower_ty = env.lookup("toLower").expect("toLower must be bound in env");
        let formatted = calvin_core::lang::types::format_mono(to_lower_ty, &HashMap::new());
        assert_eq!(formatted, "(char) -> char");

        let to_upper_ty = env.lookup("toUpper").expect("toUpper must be bound in env");
        let formatted_upper = calvin_core::lang::types::format_mono(to_upper_ty, &HashMap::new());
        assert_eq!(formatted_upper, "(char) -> char");

        // Type inference on :t toLower
        let mut typeinf = calvin_core::lang::typeinf::TypeInference::with_env_and_classes(
            &ctx,
            env.clone(),
            registry.clone(),
        );
        let ast = calvin_parse::parse_expr(&ctx, "toLower").expect("parse failed");
        let ty = typeinf.visit(ast).expect("infer failed");
        typeinf.solve_constraints().expect("solve failed");
        let residuals = typeinf.residual_constraints();
        let result = calvin_core::lang::types::format_qual_type(ty, &residuals);
        assert_eq!(result, "(char) -> char");

        let (_env, _registry, fn_defs) = init_bootstrap_with_defs(&ctx).expect("bootstrap failed");
        assert!(fn_defs.contains_key("toLower"));
        assert!(fn_defs.contains_key("toUpper"));
    }

    #[test]
    fn test_hobbes_bootstrap_type_inference() {
        let ctx = TypeContext::new();
        let (env, registry) = init_bootstrap(&ctx).expect("bootstrap failed");

        let mut typeinf = calvin_core::lang::typeinf::TypeInference::with_env_and_classes(
            &ctx,
            env.clone(),
            registry.clone(),
        );

        // 1. :t (\x y. x + y) (1.0, 2.0)
        let ast1 = calvin_parse::parse_expr(&ctx, r"(\x y. x + y) (1.0, 2.0)").expect("parse failed");
        let ty1 = typeinf.visit(ast1).expect("infer failed");
        typeinf.solve_constraints().expect("solve failed");
        let residuals1 = typeinf.residual_constraints();
        let formatted1 = calvin_core::lang::types::format_qual_type(ty1, &residuals1);
        assert_eq!(formatted1, "double");

        // 2. :t (\x -> \y -> x + y) 1.0 2.0
        let mut typeinf2 = calvin_core::lang::typeinf::TypeInference::with_env_and_classes(
            &ctx,
            env.clone(),
            registry.clone(),
        );
        let ast2 = calvin_parse::parse_expr(&ctx, r"(\x -> \y -> x + y) 1.0 2.0").expect("parse failed");
        let ty2 = typeinf2.visit(ast2).expect("infer failed");
        typeinf2.solve_constraints().expect("solve failed");
        let residuals2 = typeinf2.residual_constraints();
        let formatted2 = calvin_core::lang::types::format_qual_type(ty2, &residuals2);
        assert_eq!(formatted2, "double");
    }

    #[test]
    fn test_bootstrap_array_index_from() {
        let ctx = TypeContext::new();
        let (env, registry) = init_bootstrap(&ctx).expect("bootstrap failed");

        assert!(registry.classes.contains_key("ArrayIndex"));
        let instances = registry.instances.get("ArrayIndex").expect("ArrayIndex instances missing");
        assert_eq!(instances.len(), 4);

        let mut typeinf = calvin_core::lang::typeinf::TypeInference::with_env_and_classes(
            &ctx,
            env.clone(),
            registry.clone(),
        );
        let ast = calvin_parse::parse_expr(&ctx, "arrayIndexFrom").expect("parse failed");
        let ty = typeinf.visit(ast).expect("infer failed");
        typeinf.solve_constraints().expect("solve failed");
        let residuals = typeinf.residual_constraints();
        let formatted = calvin_core::lang::types::format_qual_type(ty, &residuals);
        assert_eq!(formatted, "ArrayIndex a => (a) -> long");

        // Application to concrete int literal: arrayIndexFrom 42
        let mut typeinf2 = calvin_core::lang::typeinf::TypeInference::with_env_and_classes(
            &ctx,
            env.clone(),
            registry.clone(),
        );
        let ast2 = calvin_parse::parse_expr(&ctx, "arrayIndexFrom 42").expect("parse failed");
        let ty2 = typeinf2.visit(ast2).expect("infer failed");
        typeinf2.solve_constraints().expect("solve failed");
        let residuals2 = typeinf2.residual_constraints();
        let formatted2 = calvin_core::lang::types::format_qual_type(ty2, &residuals2);
        assert_eq!(formatted2, "long");
    }

    #[test]
    fn test_bootstrap_convert() {
        let ctx = TypeContext::new();
        let (env, registry) = init_bootstrap(&ctx).expect("bootstrap failed");

        assert!(registry.classes.contains_key("Convert"));
        let instances = registry.instances.get("Convert").expect("Convert instances missing");
        assert!(!instances.is_empty());

        let mut typeinf = calvin_core::lang::typeinf::TypeInference::with_env_and_classes(
            &ctx,
            env.clone(),
            registry.clone(),
        );
        let ast = calvin_parse::parse_expr(&ctx, "convert").expect("parse failed");
        let ty = typeinf.visit(ast).expect("infer failed");
        typeinf.solve_constraints().expect("solve failed");
        let residuals = typeinf.residual_constraints();
        let formatted = calvin_core::lang::types::format_qual_type(ty, &residuals);
        assert_eq!(formatted, "Convert a b => (a) -> b");
    }
}
